<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sarah Gauthier">
<meta name="author" content="Nour Shawky">
<meta name="author" content="Ssemakula Peter Wasswa">
<meta name="author" content="Mehmet Imga">

<title>Image Analysis of Park Infrastructure</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="Image_analysis_of_park_infrastructure_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/popper.min.js"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Image_analysis_of_park_infrastructure_report_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Image_analysis_of_park_infrastructure_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Image_analysis_of_park_infrastructure_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Image_analysis_of_park_infrastructure_report_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="Image_analysis_of_park_infrastructure_report_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="Image_analysis_of_park_infrastructure_report_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="report-styles.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a>
  <ul class="collapse">
  <li><a href="#attribute-data" id="toc-attribute-data" class="nav-link" data-scroll-target="#attribute-data">Attribute Data</a></li>
  <li><a href="#image-data" id="toc-image-data" class="nav-link" data-scroll-target="#image-data">Image Data</a></li>
  </ul></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data Exploration</a>
  <ul class="collapse">
  <li><a href="#unique-values-and-label-consistency" id="toc-unique-values-and-label-consistency" class="nav-link" data-scroll-target="#unique-values-and-label-consistency">Unique values and label consistency</a></li>
  <li><a href="#attribute-completeness-by-asset-category" id="toc-attribute-completeness-by-asset-category" class="nav-link" data-scroll-target="#attribute-completeness-by-asset-category">Attribute completeness by asset category</a></li>
  <li><a href="#categorical-attribute-distributions" id="toc-categorical-attribute-distributions" class="nav-link" data-scroll-target="#categorical-attribute-distributions">Categorical attribute distributions</a></li>
  <li><a href="#numerical-attribute-distributions" id="toc-numerical-attribute-distributions" class="nav-link" data-scroll-target="#numerical-attribute-distributions">Numerical attribute distributions</a></li>
  <li><a href="#image-quality" id="toc-image-quality" class="nav-link" data-scroll-target="#image-quality">Image quality</a></li>
  </ul></li>
  <li><a href="#proposed-data-science-approach" id="toc-proposed-data-science-approach" class="nav-link" data-scroll-target="#proposed-data-science-approach">Proposed Data Science Approach</a></li>
  <li><a href="#evaluation-success-criteria" id="toc-evaluation-success-criteria" class="nav-link" data-scroll-target="#evaluation-success-criteria">Evaluation &amp; Success Criteria</a></li>
  <li><a href="#timeline" id="toc-timeline" class="nav-link" data-scroll-target="#timeline">Timeline</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../Image_analysis_of_park_infrastructure_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Image Analysis of Park Infrastructure</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Sarah Gauthier </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Master of Data Science, University of British Columbia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Nour Shawky </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Master of Data Science, University of British Columbia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Ssemakula Peter Wasswa </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Master of Data Science, University of British Columbia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Mehmet Imga </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Master of Data Science, University of British Columbia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This project explores how computer vision can be used to automatically extract infrastructure attributes from park images. The goal is to improve the completeness and reliability of asset management data used by BC Parks.</p>
<p>We aim to predict attributes such as asset type, material, structure position, size ranges, railing presence, and number of steps. Due to weak or incomplete labels, we adopt a staged approach that starts with a zero-shot baseline and progresses toward an attribute-specific modelling pipeline.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>BC Parks manages a large inventory of infrastructure assets such as bridges, stairs, boardwalks, and viewing platforms. While many of these assets have associated image data, the attribute information is often incomplete or inconsistent.</p>
<p>Manually reviewing thousands of images to extract attributes such as material, size, and structural features is time-consuming and not scalable. Computer vision techniques provide an opportunity to automate this process and improve data quality.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>Can machine learning models automatically predict infrastructure attributes from images, including asset type, material, size ranges, structure position, railing presence, and number of steps?</p>
</section>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">Data Sources</h2>
<p>The data for this project was exported from the CityWide asset management system using an API key provided by the project partner. It includes two primary components:</p>
<ol type="1">
<li>All image files attached to assets of type <code>Trail Bridge</code>, <code>Stairs</code>, <code>Boardwalk</code> or <code>Viewing Platform</code></li>
<li>A CSV file with attribute data for each image file</li>
</ol>
<section id="attribute-data" class="level3">
<h3 class="anchored" data-anchor-id="attribute-data">Attribute Data</h3>
<p>The CSV file with attribute data contains 5,562 rows, where each row corresponds to a single image (attachment) linked to an asset through its Asset ID. As such, the observational unit of the dataset is an individual image–asset pair. Each record also includes metadata such as image path, asset category (<code>profile_id</code>), and a series of asset-level attributes (e.g., decking material, fall height, length).</p>
<p>A summary of non-null values, data types, and number of unique values for relevant columns is shown in <a href="#tbl-data-summary" class="quarto-xref">Table&nbsp;1</a>.</p>
<div class="cell" data-execution_count="1">
<div id="tbl-data-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of non-null counts, data types, and unique values for the attribute dataset.
</figcaption>
<div aria-describedby="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Non-Null Count</th>
<th data-quarto-table-cell-role="th">Null Count</th>
<th data-quarto-table-cell-role="th">Data Type</th>
<th data-quarto-table-cell-role="th">Unique Values Count</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Column</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">image_path</td>
<td>5562</td>
<td>0</td>
<td>object</td>
<td>5562</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">file_exists</td>
<td>5562</td>
<td>0</td>
<td>bool</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">asset_id</td>
<td>5562</td>
<td>0</td>
<td>int64</td>
<td>3584</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">profile_id</td>
<td>5562</td>
<td>0</td>
<td>int64</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">profile_name</td>
<td>5562</td>
<td>0</td>
<td>object</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">description</td>
<td>5138</td>
<td>424</td>
<td>object</td>
<td>2709</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">file_id</td>
<td>5562</td>
<td>0</td>
<td>int64</td>
<td>5562</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">filename</td>
<td>5562</td>
<td>0</td>
<td>object</td>
<td>5495</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Abutment Material</td>
<td>2094</td>
<td>3468</td>
<td>object</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Bridge Type</td>
<td>2054</td>
<td>3508</td>
<td>object</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Decking Material</td>
<td>4359</td>
<td>1203</td>
<td>object</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Fall Height</td>
<td>5499</td>
<td>63</td>
<td>float64</td>
<td>36</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Has Edge Guard</td>
<td>3144</td>
<td>2418</td>
<td>object</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Has Pedestrian Railing</td>
<td>5439</td>
<td>123</td>
<td>object</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Length</td>
<td>5278</td>
<td>284</td>
<td>object</td>
<td>318</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Material (Frame, Tank, Body)</td>
<td>1958</td>
<td>3604</td>
<td>object</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Number of Steps</td>
<td>1090</td>
<td>4472</td>
<td>float64</td>
<td>19</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Structure Material</td>
<td>4355</td>
<td>1207</td>
<td>object</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">attr_Structure Position</td>
<td>1321</td>
<td>4241</td>
<td>object</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">attr_Width</td>
<td>4156</td>
<td>1406</td>
<td>object</td>
<td>96</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The columns <code>image_path</code> and <code>file_id</code> contain unique values for all rows since each image has a unique path and ID, while <code>asset_id</code> only has 3584 unique values which confirms that many assets have more than one attachment. Most of the <code>attr_</code> features represent categorical attributes while the attributes fall height and number of steps contain only numerical values. Many attributes have substantial missing data.</p>
</section>
<section id="image-data" class="level3">
<h3 class="anchored" data-anchor-id="image-data">Image Data</h3>
<p>In addition to the attribute table, the dataset includes 5,562 image files corresponding to the attachment records. These images were collected by field inspectors and serves as the input for the project’s image-analysis workflow. Examples of these images are shown in <a href="#fig-examples" class="quarto-xref">Figure&nbsp;1</a>.</p>
<div id="cell-fig-examples" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-examples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Image_analysis_of_park_infrastructure_report_files/figure-html/fig-examples-output-1.png" width="695" height="278" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Sample images from the dataset
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration">Data Exploration</h2>
<p>Exploratory data analysis (EDA) was conducted on the dataset to answer the following questions about our dataset: 1. How complete is the attribute data across different asset categories? 2. How balanced are categorical attributes across classes? 3. What is the distribution and quality of numerical attributes? 4. What is the variability in image quality across assets?</p>
<p>To answer these questions, the following analyses were performed.</p>
<section id="unique-values-and-label-consistency" class="level3">
<h3 class="anchored" data-anchor-id="unique-values-and-label-consistency">Unique values and label consistency</h3>
<p>To better understand the possible values of categorical attributes, unique values were extracted.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-unique-vals" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unique-vals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Unique values for categorical attributes
</figcaption>
<div aria-describedby="tbl-unique-vals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Column</th>
<th data-quarto-table-cell-role="th">Unique Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>attr_Abutment Material</td>
<td>Aluminum Sill Fill, Composite, Concrete, Gabions, Steel, TBD, Timber</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>attr_Bridge Type</td>
<td>Beam, Fallen Tree, Other, Suspension, TBD, TBD | Beam, Truss</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>attr_Decking Material</td>
<td>Aluminum, Asphalt, Composite, Concrete, Steel, TBD, Timber</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>attr_Has Edge Guard</td>
<td>No, TBD, Yes</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>attr_Has Pedestrian Railing</td>
<td>1 railing, 2 railings, No, No railings, TBD, TBD | No railings, TBD | Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>attr_Material (Frame, Tank, Body)</td>
<td>Aluminum, Box Step, Concrete, Earth-Filled, Gravel, Metal, Natural Surface, PVC, Rock/Stone, Steel, TBD, Timber/Wood</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>attr_Structure Material</td>
<td>Aluminum, Concrete, Steel, Stone, TBD, Timber</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>attr_Structure Position</td>
<td>At-Grade, Elevated, Other, TBD</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-unique-vals" class="quarto-xref">Table&nbsp;2</a> reveals some data quality issues such as the presence of placeholder values like <code>TBD</code> to denote missing values. There are also some redundant category labels (e.g., <code>No</code> and <code>No railings</code>) that should be combined into one category.</p>
<p>Additionally, it was found that numerical fields contained invalid placeholders such as <code>-1</code> or <code>0</code>, which also artificially reduce the null counts in <a href="#tbl-data-summary" class="quarto-xref">Table&nbsp;1</a>.</p>
</section>
<section id="attribute-completeness-by-asset-category" class="level3">
<h3 class="anchored" data-anchor-id="attribute-completeness-by-asset-category">Attribute completeness by asset category</h3>
<p>To assess data coverage, attribute fill rates were computed for each asset category. This is necessary because not all attributes are relevant to all asset types (e.g., <code>Number of Steps</code> is only applicable to stairs). Invalid placeholder values were removed before computing completeness.</p>
<div id="fig-attribute-fill-rate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-attribute-fill-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_images/attribute_fill_rate.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-attribute-fill-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Attribute fill rate per asset category
</figcaption>
</figure>
</div>
<p><a href="#fig-attribute-fill-rate" class="quarto-xref">Figure&nbsp;2</a> shows variation in completeness across both attributes and asset types. Numerical attributes such as <code>Fall Height</code> and <code>Number of Steps</code> are particularly sparse while some categorical attributes like <code>Decking Material</code> are more consistently filled. This indicates that attribute collection is inconsistent and may require imputation or alternative learning strategies, including leveraging image-based inference or pre-trained models.</p>
</section>
<section id="categorical-attribute-distributions" class="level3">
<h3 class="anchored" data-anchor-id="categorical-attribute-distributions">Categorical attribute distributions</h3>
<div id="fig-cat-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cat-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_images/categorical_distributions.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cat-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Class distributions for categorical attributes
</figcaption>
</figure>
</div>
<p><a href="#fig-cat-distributions" class="quarto-xref">Figure&nbsp;3</a> shows strong class imbalance across several categorical attributes. For example, for <code>Decking Material</code> and <code>Structure Material</code>, dominant classes such as <code>Timber</code> appear far more frequently than alternatives. This imbalance introduces bias risks for supervised learning, as models may over-predict majority classes and underperform on rare categories. As a result, evaluation metrics such as precision and recall will be more appropriate than overall accuracy. This also motivates the use of a majority-class baseline model for benchmarking.</p>
</section>
<section id="numerical-attribute-distributions" class="level3">
<h3 class="anchored" data-anchor-id="numerical-attribute-distributions">Numerical attribute distributions</h3>
<div id="fig-num-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-num-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_images/numerical_distributions.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-num-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Numerical attribute distributions
</figcaption>
</figure>
</div>
<p>Numerical attributes were analysed using histograms with mean and median values. These distributions are highly skewed, with clear differences between mean and median, indicating outliers and possibly inconsistent measurement practices.</p>
</section>
<section id="image-quality" class="level3">
<h3 class="anchored" data-anchor-id="image-quality">Image quality</h3>
<p>While having multiple images per asset improves coverage, image quality is highly variable. Some images are close-ups or poorly framed, and may not capture relevant structural information.</p>
<p>As shown in <a href="#fig-same-asset" class="quarto-xref">Figure&nbsp;5</a>, even images from the same asset can vary significantly in usefulness. This suggests that image filtering or weighting may be required during model training to reduce noise from low-quality samples.</p>
<div id="cell-fig-same-asset" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-same-asset" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-same-asset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Image_analysis_of_park_infrastructure_report_files/figure-html/fig-same-asset-output-1.png" width="623" height="307" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-same-asset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Two sample images of the same boardwalk
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="proposed-data-science-approach" class="level2">
<h2 class="anchored" data-anchor-id="proposed-data-science-approach">Proposed Data Science Approach</h2>
<p>Our approach is motivated directly by the findings from our exploratory data analysis above. Given the high degree of class imbalance seen in <a href="#fig-cat-distributions" class="quarto-xref">Figure&nbsp;3</a>, we will start by defining a majority class predictor as our simplest benchmark, which always predicts the most frequent class per attribute. This sets a minimum performance floor: any model that cannot outperform this baseline provides no added value in our pipeline. We’ll be relying on F1 score to get a true picture of our baseline performance.</p>
<p>As we have seen above in <a href="#tbl-unique-vals" class="quarto-xref">Table&nbsp;2</a>, not all attributes are the same. They vary in type, difficulty and which asset types they apply to. Categorical attributes will require a classification approach while numerical attributes like length and fall height are better treated as ordered categories due to the difficulty in estimating exact measurements from images without a size reference to work with. Our pipeline therefore routes each image to the relevant set of attribute predictions based on the asset type, which is provided by BCParks via an organized folder structure. See <a href="#fig-pipeline" class="quarto-xref">Figure&nbsp;6</a>.</p>
<p>Given that a large proportion of our attribute labels are missing or incomplete, our next step is to explore zero-shot approaches that require no labelled training data. We will first evaluate a zero-shot Vision Language Model (VLM), building directly on the partner’s existing work with VLMs for attribute labelling. Through careful prompt configuration and providing the model with all possible attribute labels, we can establish a strong benchmark without any fine-tuning. Other zero-shot models like CLIP will be used for performance comparison.</p>
<p>To improve VLM performance, we will also implement a few-shot approach where we provide a small subset of labelled images alongside the prompt, which can improve prediction quality without full training. A key advantage of this approach is its flexibility: the model can also be prompted to return “Cannot Determine” or “Requires Manual Review” when an image does not contain sufficient information, such as close-up or low-quality photos. However, the main challenge with these approaches is that performance depends heavily on prompt and description quality, and they may struggle with fine-grained visual details and recognizing rare attribute values.</p>
<p>Lastly, we will also explore more advanced methods that make use of our available labelled data as well as some external data that may help support training. This includes training lightweight classifiers on top of rich pre-trained embeddings, which work well even with small datasets and are particularly effective for material-based attributes. As a stretch goal, we will also explore combining visual similarity search with a language model (RAG), where similar labelled images are retrieved and used as context to inform predictions made by a VLM.</p>
<p>All approaches will produce a CSV file with all attribute predictions alongside a confidence score, with low confidence predictions being flagged for manual review by BCParks.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-pipeline">flowchart TD
    A["Image Folder per Asset Type"] --&gt; B["Image FilteringYOLO or Model Prompt"]
    B --&gt; C["Attribute Prediction Zero-shot VLM / CLIP"]
    C --&gt; D["CSV OutputPredictions + Confidence Scores"]
    C --&gt; E["Advanced Approaches DINOv2 / RAG"]
    E --&gt; D
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: High-level overview of the proposed attribute prediction pipeline
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="evaluation-success-criteria" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-success-criteria">Evaluation &amp; Success Criteria</h2>
</section>
<section id="timeline" class="level2">
<h2 class="anchored" data-anchor-id="timeline">Timeline</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Week</th>
<th>Focus</th>
<th>Key Deliverables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Data understanding &amp; preliminary EDA</td>
<td>Completeness analysis, class distribution plots, preliminary EDA notebook, proposal presentation</td>
</tr>
<tr class="even">
<td>2</td>
<td>Data cleaning &amp; preprocessing</td>
<td>More EDA, extract data quality isssues, prepare cleaned master dataset + asset specific datasets, proposal report submitted</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Baseline &amp; zero shot models</td>
<td>Train/val/test splits, Majority class predictor, zero-shot VLM and CLIP evaluation, prompt refinement, few-shot VLM</td>
</tr>
<tr class="even">
<td>4-5</td>
<td>Experimenting with Complex Approaches</td>
<td>Embedding (DINOv2) + classifier approach , asset-specific models, RAG pipeline implementation</td>
</tr>
<tr class="odd">
<td>6–8</td>
<td>Model evaluation &amp; Fine Tuning, Finalization of data product</td>
<td>Best model fine-tuning, Model evaluation and comparison, final evaluation on held-out test set, final report + data product, partner documentation and demo</td>
</tr>
</tbody>
</table>
<p><em>Note: Data cleaning, preprocessing and transformations will be refined continuously throughout the project as new challenges or changes to modelling approaches emerge.</em></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>